openapi: 3.0.0
info:
  title: Football Competition Management API
  version: 1.0.0
  description: Simple API for managing football competitions, teams, and players.

paths:
  /competitions:
    get:
      summary: Get all competitions
      responses:
        '200':
          description: List of competitions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Competition'
    post:
      summary: Create a new competition
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Competition'
      responses:
        '201':
          description: Competition created

  /teams:
    get:
      summary: Get all teams
      responses:
        '200':
          description: List of teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
    post:
      summary: Create a new team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
      responses:
        '201':
          description: Team created

  /teams/{teamId}/players:
    get:
      summary: Get players in a team
      parameters:
        - name: teamId
          in: path
          required: true
          schema:
            type: string
          description: ID of the team
      responses:
        '200':
          description: List of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
    post:
      summary: Add players to a team
      parameters:
        - name: teamId
          in: path
          required: true
          schema:
            type: string
          description: ID of the team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Player'
      responses:
        '201':
          description: Players added

components:
  schemas:
    Competition:
      type: object
      properties:
        name:
          type: string
          example: LIGA
        location:
          type: string
          example: SPAIN
    Team:
      type: object
      properties:
        name:
          type: string
          example: Real Madrid
        slogan:
          type: string
          example: Hala Madrid
    Player:
      type: object
      properties:
        name:
          type: string
          example: Lionel Messi
        number:
          type: integer
          example: 10
        strongFoot:
          type: string
          enum:
            - Left
            - Right
